#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# root level inclusions
#------------------------------------------------------------------------------
.gitignore=
pom.xml=
pom*.xml=
Dockerfile=
entrypoint.sh
build.xml=
README.md=


# django root related
manage.py=.

# django mainsite related
settings.py=.mainsite
wsgi.py=.mainsite

# django app related
__classes__.py=.models
__classes__Delegate.py=.delegates
__classes__Test.py=.tests
__classes__View.py=.views
__classes__Urls.py=.urls
__enums__.py=.models
Exceptions.py=.exceptions
empty.doc=.docs
admin.py=.
apps.py=.
appUrls.py=.
setup.py=.
README.rst=.
LICENSE=.

pytest.ini=.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.mainsite,.models,.delegates,.tests,.views,.urls,.exceptions

exclusions=mappings.properties,options.json,blueprint.json