#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# root level inclusions
#------------------------------------------------------------------------------
.gitignore=
pom.xml=
pom*.xml=
Dockerfile=
entrypoint.sh
build.xml=
README.md=



#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.bankingsystem
requirements.txt=.bankingsystem
admin.py=.bankingsystem
apps.py=.bankingsystem
appUrls.py=.bankingsystem
setup.py=.bankingsystem
README.rst=.bankingsystem
LICENSE=.bankingsystem

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.$lowercaseAppName.mainsite
wsgi.py=..$lowercaseAppName.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=..$lowercaseAppName.models
__classes__Delegate.py=..$lowercaseAppName.delegates
__classes__Test.py=..$lowercaseAppName.tests
__classes__View.py=..$lowercaseAppName.views
__classes__Urls.py=..$lowercaseAppName.urls
__enums__.py=..$lowercaseAppName.models
Exceptions.py=..$lowercaseAppName.exceptions
empty.doc=..$lowercaseAppName.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=..$lowercaseAppName.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=..$lowercaseAppName.mainsite,..$lowercaseAppName.models,..$lowercaseAppName.delegates,..$lowercaseAppName.tests,..$lowercaseAppName.views,..$lowercaseAppName.urls,..$lowercaseAppName.exceptions

exclusions=mappings.properties,options.json,blueprint.json