#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# root level inclusions
#------------------------------------------------------------------------------
.gitignore=
pom.xml=
pom*.xml=
Dockerfile=
entrypoint.sh
build.xml=
README.md=



#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.bankingSystem
requirements.txt=.bankingSystem
admin.py=.bankingSystem
apps.py=.bankingSystem
appUrls.py=.bankingSystem
setup.py=.bankingSystem
README.rst=.bankingSystem
LICENSE=.bankingSystem

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.bankingSystem.mainsite
wsgi.py=.bankingSystem.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.bankingSystem.models
__classes__Delegate.py=.bankingSystem.delegates
__classes__Test.py=.bankingSystem.tests
__classes__View.py=.bankingSystem.views
__classes__Urls.py=.bankingSystem.urls
__enums__.py=.bankingSystem.models
Exceptions.py=.bankingSystem.exceptions
empty.doc=.bankingSystem.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.bankingSystem.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.bankingSystem.mainsite,.bankingSystem.models,.bankingSystem.delegates,.bankingSystem.tests,.bankingSystem.views,.bankingSystem.urls,.bankingSystem.exceptions

exclusions=mappings.properties,options.json,blueprint.json